### ISSUE TITLE
The most basic hello world fails

### ISSUE THREAD

**Issue by eric-at-rebounded** [balexand/gql#29]
iex(2)> url = "https://api.spacex.land/graphql/"
"https://api.spacex.land/graphql/"
iex(3)> GQL.query("query Launches { launches { id } }", url: url)
** (GQL.ConnectionError) %GQL.ConnectionError{reason: :nxdomain}
    (gql 0.6.2) lib/gql.ex:123: GQL.query/2
    iex:3: (file)
iex(3)>

this is running inside my dev container based on elixir:1.14.2-alpine

**Comment by balexand** [comment]
You're most basic hello world is using a domain name that doesn't resolve to anything, hence the `:nxdomain` error. I'll update the README (https://github.com/balexand/gql/issues/30).
